### ISSUE TITLE
Better exception handling

### ISSUE THREAD

**Issue by illiriks** [niko-reingold/Bandwidth#3]
Right now, all that is done is a stack trace is printed. The user of the app would have no idea that something errored. Perhaps alert the user that there was a failure? The Bandwidth SDKs may provide documentation about the kinds of exceptions they throw which might motivate descriptive error messages sent to the browser, rather than the client.

**Comment by niko-reingold** [comment]
Updated exceptions to be more specific when possible.  Some exceptions are still stack trace, because there wasn't anything more specific in the sdk.
